language: go

go:
  #- 1.5.2
  #- 1.6.1
  - 1.8.x
  - tip

addons:
  firefox: 53.0.3 #latest

env:
  global:
    - DISPLAY=:99.0

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - sh -e /etc/init.d/xvfb start

before_script:
  - firefox --version
  - firefox -marionette > /dev/null 2>&1 &
  - sleep 5
  - ps aux | grep firefox

script:
  #- go test -test.v
  - go test -test.v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - $HOME/gopath/bin/goveralls -service=travis-ci